# Generated by Django 5.1.5 on 2025-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_sample_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
