# Generated by Django 5.1.5 on 2025-03-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_location_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_url',
        ),
    ]
