# Generated by Django 5.1.5 on 2025-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("BEIRUT", "Beirut"),
                            ("BAALBAK", "Baalbak"),
                            ("BATROUN", "Batroun"),
                            ("BYBLOS", "Byblos"),
                            ("SIDON", "Sidon"),
                            ("SOUR", "Sour"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HISTORICAL", "Historical sites"),
                            ("RESTAURANT", "Restaurants"),
                            ("BEACH", "Beaches"),
                            ("COFFEE", "Coffee shops"),
                            ("HOTEL", "Hotels"),
                            ("NIGHTLIFE", "Night life"),
                            ("MUSEUM", "Museums"),
                            ("ACTIVITY", "Activities"),
                        ],
                        max_length=10,
                    ),
                ),
                ("max_people", models.PositiveIntegerField()),
                ("current_people", models.PositiveIntegerField(default=0)),
                ("cost_range", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("ticket_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
