# Generated by Django 5.1.7 on 2025-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mohafaza', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('HISTORICAL', 'Historical'), ('NATURAL', 'Natural'), ('CULTURAL', 'Cultural'), ('ADVENTURE', 'Adventure'), ('FOOD', 'Food'), ('SHOPPING', 'Shopping'), ('NIGHTLIFE', 'Nightlife'), ('OTHER', 'Other')], max_length=20)),
                ('max_people', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='locations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
