# Generated by Django 5.1.7 on 2025-03-14 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='location',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
