# Generated by Django 5.1.5 on 2025-04-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="current_people",
        ),
        migrations.RemoveField(
            model_name="location",
            name="max_people",
        ),
        migrations.AlterField(
            model_name="location",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
