# Generated by Django 5.1.5 on 2025-04-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('HISTORICAL', 'Historical sites'), ('RESTAURANTS', 'Restaurants'), ('BEACHES', 'Beaches'), ('COFFEE_SHOPS', 'Coffee shops'), ('HOTELS', 'Hotels'), ('NIGHTLIFE', 'Night life'), ('MUSEUMS', 'Museums'), ('ACTIVITIES', 'Activities')], max_length=20),
        ),
    ]
