# Generated by Django 5.1.5 on 2025-04-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_remove_location_current_people_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
