# Generated by Django 5.1.5 on 2025-03-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_picture_url_alter_location_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='mohafaza',
        ),
    ]
