# Generated by Django 5.1.5 on 2025-04-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_category'),
    ]

    operations = [
    ]
