# Generated by Django 5.1.5 on 2025-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_alter_location_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="current_people",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="max_people",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
